defaults: &defaults
  login: '<%= ENV["GIT_LOGIN"] %>'
  password: '<%= ENV["GIT_PASS"] %>'
  repo_path: '<%= ENV["GIT_REPO"] %>'
  repo_ssh_url: '<%= ENV["GIT_SSH_URL"] %>'
  local_repo: '<%= ENV["GIT_LOCAL_REPO"] %>'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
