require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StageCommitsController do

  # This should return the minimal set of attributes required to create a valid
  # StageCommit. As you add validations to StageCommit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sha" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StageCommitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stage_commits as @stage_commits" do
      stage_commit = StageCommit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stage_commits).should eq([stage_commit])
    end
  end

  describe "GET show" do
    it "assigns the requested stage_commit as @stage_commit" do
      stage_commit = StageCommit.create! valid_attributes
      get :show, {:id => stage_commit.to_param}, valid_session
      assigns(:stage_commit).should eq(stage_commit)
    end
  end

  describe "GET new" do
    it "assigns a new stage_commit as @stage_commit" do
      get :new, {}, valid_session
      assigns(:stage_commit).should be_a_new(StageCommit)
    end
  end

  describe "GET edit" do
    it "assigns the requested stage_commit as @stage_commit" do
      stage_commit = StageCommit.create! valid_attributes
      get :edit, {:id => stage_commit.to_param}, valid_session
      assigns(:stage_commit).should eq(stage_commit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StageCommit" do
        expect {
          post :create, {:stage_commit => valid_attributes}, valid_session
        }.to change(StageCommit, :count).by(1)
      end

      it "assigns a newly created stage_commit as @stage_commit" do
        post :create, {:stage_commit => valid_attributes}, valid_session
        assigns(:stage_commit).should be_a(StageCommit)
        assigns(:stage_commit).should be_persisted
      end

      it "redirects to the created stage_commit" do
        post :create, {:stage_commit => valid_attributes}, valid_session
        response.should redirect_to(StageCommit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stage_commit as @stage_commit" do
        # Trigger the behavior that occurs when invalid params are submitted
        StageCommit.any_instance.stub(:save).and_return(false)
        post :create, {:stage_commit => { "sha" => "invalid value" }}, valid_session
        assigns(:stage_commit).should be_a_new(StageCommit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StageCommit.any_instance.stub(:save).and_return(false)
        post :create, {:stage_commit => { "sha" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stage_commit" do
        stage_commit = StageCommit.create! valid_attributes
        # Assuming there are no other stage_commits in the database, this
        # specifies that the StageCommit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StageCommit.any_instance.should_receive(:update).with({ "sha" => "MyString" })
        put :update, {:id => stage_commit.to_param, :stage_commit => { "sha" => "MyString" }}, valid_session
      end

      it "assigns the requested stage_commit as @stage_commit" do
        stage_commit = StageCommit.create! valid_attributes
        put :update, {:id => stage_commit.to_param, :stage_commit => valid_attributes}, valid_session
        assigns(:stage_commit).should eq(stage_commit)
      end

      it "redirects to the stage_commit" do
        stage_commit = StageCommit.create! valid_attributes
        put :update, {:id => stage_commit.to_param, :stage_commit => valid_attributes}, valid_session
        response.should redirect_to(stage_commit)
      end
    end

    describe "with invalid params" do
      it "assigns the stage_commit as @stage_commit" do
        stage_commit = StageCommit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StageCommit.any_instance.stub(:save).and_return(false)
        put :update, {:id => stage_commit.to_param, :stage_commit => { "sha" => "invalid value" }}, valid_session
        assigns(:stage_commit).should eq(stage_commit)
      end

      it "re-renders the 'edit' template" do
        stage_commit = StageCommit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StageCommit.any_instance.stub(:save).and_return(false)
        put :update, {:id => stage_commit.to_param, :stage_commit => { "sha" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stage_commit" do
      stage_commit = StageCommit.create! valid_attributes
      expect {
        delete :destroy, {:id => stage_commit.to_param}, valid_session
      }.to change(StageCommit, :count).by(-1)
    end

    it "redirects to the stage_commits list" do
      stage_commit = StageCommit.create! valid_attributes
      delete :destroy, {:id => stage_commit.to_param}, valid_session
      response.should redirect_to(stage_commits_url)
    end
  end

end
